# ADAPT THIS FILE WITH YOUR CREDENTIALS AND RENAME IT "my_credentials.R"
dataverse_server="one-dataverse.org"
dataverse_key="243df-apikey-41df2-52f-52df42ds23f"
dataverse_name="dataverse_id_as_it_appears_in_the_url_of_the_dataverse"
dataverse_user_name="Snow, Jon"
my_wd="~/SomeWhereGitRepositories/R_Metadata/"
